const doesThisSoundFamiliar = [
    "Sorry for taking a week to text you back, I forgot I read your message.",
    "It's okay not everyone can be funny like me",
    "It's me and my 4 hours of sleep against the world",
    "Thanks for pretending to like me",
    "No offense to myself but wtf am i even doing these days",
    "maybe i should just start a cult",
    "match my freak (do nothing but still gets tired)",
    "I googled my symptoms, turns out I needed therapy",
    "i'd be so unstoppable if i wasn't sleepy all the time",
    "if ur crazy and obsessive hmu",
    'i be like "idgaf" then talk to myself about it for 4 days',
    "that random memory in 5th grade that makes me wanna die",
    "i'm a mess but i'm a cute mess",
    "compliment me once and i will start imgining our entire future together",
    "social media is literally a simulation wtf",
    'i keep saying "it is what it is" but what even is it',
    "it'll be really funny when you never hear from me again",
    "i'm a walking contradiction",
    "life gets so much easier when you pretend people you don't like doens't exist",
    "trauma?? oh you mean my lore",
    "i'm fragile but not like a glass of flower, more like a bomb",
    "i'm not a snack, i'm a whole meal",
    "just opened up a can of worms and now i'm playing with them",
    "just opened the fridge for the 13th time hoping something new will appear",
    "am i dissociating or just tired",
    "am i distracting myself again? yes",
    "my hobbies are crying and sleeping",
    "my hobbies are doing whatever you like to do",
    "sometimes i think i'm a genius and then i do something stupid",
]